- title: "Blaze Foley | Drunkin No 3 | 1973 "
  name: "disc01BlazeFoley.txt"
  image: ""

- title: "Follakzoid"
  name: "disc02Follakzoid.txt"
  image: ""

- title: "Danger Mouse"
  name: "disc03DangerMouse.txt"
  image: ""
