- title: "SITTIN' BY THE ROAD | BLAZE FOLEY | 2010"
  name: "disc001.txt"
  image: ""

- title: "V | FOLLAKZOID | 2023"
  name: "disc002.txt"
  image: ""

- title: "THE GREY ALBUM | DANGER MOUSE | 2004"
  name: "disc003.txt"
  image: ""

- title: "I LOVE YOU JENNIFER B | JOCKSTRAP | 2022"
  name: "disc004.txt"
  image: ""

- title: "MINECRAFT VOLUME ALPHA | C418 | 2011"
  name: "disc005.txt"
  image: ""

- title: "MADVILLAINY | MADVILLAIN | 2004"
  name: "disc006.txt"
  image: ""

- title: "THREE BELLS | TY SEGALL | 2024"
  name: "disc007.txt"
  image: ""

- title: "ELEGANT GYPSY | AL DI MEOLA | 1977"
  name: "disc008.txt"
  image: ""

- title: "DEATHCONSCIOUSNESS | HAVE A NICE LIFE | 2008"
  name: "disc009.txt"
  image: ""

- title: "ATLAS | YO SOY MATT | 2019"
  name: "disc010.txt"
  image: ""

- title: "SUBMERSIVE BEHAVIOUR | TROPICAL FUCK STORM | 2023"
  name: "disc011.txt"
  image: ""

- title: "LOSS OF LIFE | MGMT | 2024"
  name: "disc012.txt"
  image: ""

- title: "THE DARK SIDE OF THE MOON REDUX | ROGER WATERS | 2023"
  name: "disc013.txt"
  image: ""

- title: "AGAIN | ONEOHTRIX POINT NEVER | 2023"
  name: "disc014.txt"
  image: ""

- title: "HOW TO SURVIVE A BAD TRIP | YSSUE | 2024"
  name: "disc015.txt"
  image: ""

- title: "GOD GAMES | THE KILLS | 2023"
  name: "disc016.txt"
  image: ""

- title: "ROOTS | SEPULTRA | 1996"
  name: "disc017.txt"
  image: ""

- title: "RIKI | RIKI | 2020"
  name: "disc018.txt"
  image: ""

- title: "POSITIVE FORCE | DELICATE STEVE | 2012"
  name: "disc019.txt"
  image: ""

- title: "KOMARA | KOMARA | 2015"
  name: "disc020.txt"
  image: ""

- title: "HIT ME HARD AND SOFT | BILLIE EILISH | 2024"
  name: "disc021.txt"
  image: ""

- title: "LES MISÉRABLES SOUNDTRACK | CLAUDE-MICHEL SCHÖNBERG | 2012"
  name: "disc022.txt"
  image: ""

- title: "AT FOLSOM PRISON | JOHNNY CASH | 1968"
  name: "disc023.txt"
  image: ""

- title: "ANTITIMOROUMENI | Ὁπλίτης | 2023"
  name: "disc024.txt"
  image: ""

- title: "AWAKEN, MY LOVE! | CHILDISH GAMBINO | 2016"
  name: "disc025.txt"
  image: ""

- title: "EMPATHOGEN | WILLOW | 2024"
  name: "disc026.txt"
  image: ""

- title: "AUTOMATIC | MILDLIFE | 2020"
  name: "disc027.txt"
  image: ""

- title: "IRRESISTIBLE BLISS | SOUL COUGHING | 1996"
  name: "disc028.txt"
  image: ""

- title: "WHERE'S MY UTOPIA | YARD ACT | 2024"
  name: "disc029.txt"
  image: ""

- title: "HIGHWAYMAN 2 | THE HIGHWAYMEN | 1990"
  name: "disc030.txt"
  image: ""

- title: "SCARING THE HOES | JPEG MAFIA / DANNY BROWN | 2023"
  name: "disc031.txt"
  image: ""

- title: "DISCO :: 4 PART II | HEALTH | 2022"
  name: "disc032.txt"
  image: ""

- title: "ILLMATIC | NAS | 1994"
  name: "disc033.txt"
  image: ""

- title: "NO NAME | JACK WHITE | 2024"
  name: "disc034.txt"
  image: ""

- title: "NAQI VOL I & II | MANSUR BROWN | 2022"
  name: "disc035.txt"
  image: ""

- title: "ROMANCE | FONTAINES DC | 2024"
  name: "disc036.txt"
  image: ""

- title: "KNOCKNAREA | MARUJA | 2023"
  name: "disc037.txt"
  image: ""

- title: "MIRRORS, JEUX D'EAUX, PAVANE POUR UNE INFANTE DÉFUNTE | MAURICE RAVEL / ANDRÉ LAPLANTE | 2005"
  name: "disc038.txt"
  image: ""

- title: "THE BIRD OF A THOUSAND VOICES | TIGRAN HAMASYAN | 2024"
  name: "disc039.txt"
  image: ""

- title: "RUBBER FACTORY | THE BLACK KEYS | 2004"
  name: "disc040.txt"
  image: ""

- title: "LAHAI | SAMPHA | 2023"
  name: "disc041.txt"
  image: ""

- title: "WOKE UP RIGHT HANDED | BLAWAN | 2021"
  name: "disc042.txt"
  image: ""

- title: "CRUMBLING | MID-AIR THIEF | 2018"
  name: "disc043.txt"
  image: ""

- title: "THE NEW SOUND | GEORDIE GREEP | 2024"
  name: "disc044.txt"
  image: ""

- title: "BARREN COUNTRY | NEW GRASS REVIVAL | 1979"
  name: "disc045.txt"
  image: ""

- title: "BYTE BYTE | CHIP TORRES | 2021"
  name: "disc046.txt"
  image: ""

- title: "TEATRO LÚCIDO | LA FEMME | 2022"
  name: "disc047.txt"
  image: ""
