name: sync to s3
on:
  push:
    branches:
      - main
jobs:
  sync_to_s3:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: sync to s3
        run: |
          aws s3 sync --delete --exclude "README.md" --exclude ".github/*" --exclude ".git/*" --exclude ".gitignore" . s3://${{ secrets.AWS_BUCKET }}
