name: sync to s3
on:
  push:
    branches:
      - main
permissions:
  id-token: write
jobs:
  sync_to_s3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@main
      - name: debug secrets
        run: |
          echo "AWS_BUCKET is ${AWS_BUCKET:+set}"
          echo "AWS_REGION is ${AWS_REGION:+set}"
          echo "AWS_ROLE_ARN is ${AWS_ROLE_ARN:+set}"
          pwd
          ls
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: sync to s3
        run: |
          aws s3 sync --delete --exclude "README.md" --exclude ".github/*" --exclude ".git/*" --exclude ".gitignore" . s3://${{ secrets.AWS_BUCKET }}
